# These are supported funding model platforms

github: 
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom: ['https://boosty.to/noex75', 'https://www.donationalerts.com/r/noex75', 'https://tonkeeper.com/transfer/UQDygpeCDjqc4hWOH8hOWnNeYopKDKps5oroj42ULWVC0nMl']
